[phases.setup]
nixPkgs = ['python311', 'nodePackages.nodejs']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'echo "Build completed successfully"'
]

[start]
cmd = './start.sh'